# Generated by Django 5.2.4 on 2025-07-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatDot', '0002_alter_user_fullname_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.BigIntegerField(max_length=10)),
                ('last_generated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
