# Generated by Django 5.2.4 on 2025-07-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatDot', '0003_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='otp',
            field=models.BigIntegerField(),
        ),
    ]
