# Generated by Django 5.2.4 on 2025-08-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatDot', '0008_alter_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequests',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
