# Generated by Django 5.2.4 on 2025-08-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatDot', '0009_friendrequests_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
